# Site title and description
title: Flutter Docs
description: Find, Learn, Love...
lang: en

# Site subpath, e.g. /blog
baseurl: ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:title/

# Site base hostname & protocol, e.g. http://example.com
url: ""

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo: flutter-logo.png

navbar:
  sticky: true
  search: true

# Social icons displayed in footer
social:
  email:
  website:
  facebook:
  flickr:
  dribbble:
  github:
  googleplus:
  instagram:
  linkedin:
  pinterest:
  twitter:
  vimeo:
  youtube:

# Share button
share:
  post: true # Display share buttons on a post page
  doc: true # Display share buttons on a doc page
  twitter: username # Enable by adding Twitter handle
  facebook: true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
  copyright: Copyright@2021 <a href="https://www.flutter.com/" target="_">Flutter</a>

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
  shortname: # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Path to post content assets directory i.e post images, pdfs etc
uploads: /uploads/

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style: compressed

collections:
  docs:
    output: true
  tutorials:
    output: true
  faqs:
    output: false
  changelogs:
    output: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
