# .github/workflows/git-sync.yml

on:
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    name: Sync external doc site
    environment: prod
    steps:
      - name: Retrieve the Flutter Global app token
        id: flutter_global_app
        uses: Flutter-Tech/github-app-token@6975143c1cf1a5c6cb1823d532778402d3608505
        with:
          APP_PEM: ${{ secrets.FLUTTER_GLOBAL_PEM }}
          APP_ID: 115213
          APP_INSTALLATION_ID: 16908128

      - name: Retrieve the Flutter Tech app token
        id: flutter_tech_app
        uses: Flutter-Tech/github-app-token@6975143c1cf1a5c6cb1823d532778402d3608505
        with:
          APP_PEM: ${{ secrets.FLUTTER_TECH_PEM }}
          APP_ID: 115232
          APP_INSTALLATION_ID: 16910369

      - name: Check Flutter Global Token is valid
        uses: actions/github-script@v4
        with:
          github-token: ${{ steps.flutter_global_app.outputs.app_token }}
          script: |
            github.repos.get({owner: "Flutter-Global", repo: "fsc-docs-site"})

      - name: Clone FG docs site
        uses: actions/checkout@v2

      - name: Push to FT
        run: |
          git remote add destination "https://${{ steps.flutter_tech_app.outputs.app_token }}:x-oauth-basic@github.com/Flutter-Tech/fsc-docs-site.git"
          git push destination "main:main" -f
