name: Deploy GH Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    # skip this job unless in Flutter-Tech repo
    if: ${{ github.repository_owner == 'Flutter-Tech' }}
    runs-on: ubuntu-latest
    environment: github-pages
    concurrency: deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - uses: actions/setup-node@v2

      - run: npm install

      - name: Build website
        run: bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

