name: Update CLI Release

on:
  workflow_dispatch:
  # run daily to catch releases
  schedule:
    - cron: "30 3 * * *"

jobs:
  update-cli:
    # skip this job if running in the target Flutter-Tech repo
    if: ${{ github.repository_owner != 'Flutter-Tech' }}
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Retrieve Flutter Global app token
        id: flutter_global_app_token
        uses: Flutter-Tech/github-app-token@v1
        with:
          APP_PEM: ${{ secrets.FLUTTER_GLOBAL_PEM }}
          APP_ID: 115213
          APP_INSTALLATION_ID: 16908128

      - name: Checkout docs site
        uses: actions/checkout@v2
        with:
          token: ${{ steps.flutter_global_app_token.outputs.app_token }}

      # run node script to update cli if necessary
      - name: Update CLI script
        env:
          ORG_TOKEN: ${{ steps.flutter_global_app_token.outputs.app_token }}
        run: |
          cd _script
          npm install
          node update-cli.js
          cd ..
          ls -alh ./git-flutter/

      - name: Commit changes to site
        run: |
          if [ ! -z "$(git status --porcelain=v1 2>/dev/null)" ]
          then
            git config --global user.email "innersource-bot@flutter.com"
            git config --global user.name "Inner source bot"
            git add .
            git commit -m "Update CLI version"
            git push
          fi
